version: '3.7'
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=db